language: node_js
node_js:
  - node
  - lts/*
install:
  - npm install
before_script: 
  - npm rebuild node-sass
script:
  # - npm run lint:styles
  # - npm run lint:js
  # - npm run lint:html
  - npm run build
deploy:
  provider: pages
  cleanup: false
  github_token: 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
  keep_history: true
  local_dir: dist
  on:
    branch: master
    node: 'lts/*'
