language: node_js
node_js:
  - node
  - lts/*
install:
  - npm install
before_script: 
  - npm rebuild node-sass
script:
  # - npm run lint:styles
  # - npm run lint:js
  # - npm run lint:html
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 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
  keep-history: true
  local-dir: dist
  on:
    branch: master
    node: 'lts/*'
